### ISSUE TITLE
Add Spam Filter to image search

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#581] opened 2019-10-10 12:51 UTC
I have attempted to do a spam filter that downranks domains identified as spam in the image search results with a list of about 300 spam domains.

The results were quite slow as expected, so the filter was not applied.

In the future add to each SOLR document a "Spam_score" and then downrank results with higher value in this field in the image search API.

**Comment by amourao** [comment] 2020-02-07 16:16
Duplicate of #546.

**Closed by amourao** 2020-02-07 16:16 UTC
Labels: Component-SearchImages-ImageSearchAPI
