### ISSUE TITLE
Error processing anchors on Wayback URLS

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#226] opened 2016-07-29 09:52 UTC
Access:
http://arquivo.pt/wayback/20131107225721/http://www.odu.edu/#prospective

Copy the URL:
"http://arquivo.pt/wayback/20131107225721/http://www.odu.edu/#prospective"

Paste on the browser navbar.

Goes to the previous version:
http://arquivo.pt/wayback/19961013153010/http://www.odu.edu/index.html#prospective

If we remove the anchor "#prospective" it works fine:
http://arquivo.pt/wayback/20131107225721/http://www.odu.edu/

**Comment by Fernando-Melo** [comment] 2018-08-17 10:57
cannot reproduce maybe it was fixed by new pywb

**Closed by Fernando-Melo** 2018-08-17 10:57 UTC
Labels: Component-Wayback, Impact-Low, Type-Bug
