### ISSUE TITLE
Add the collection parameter to the Image Search API

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#561] opened 2019-08-13 15:35 UTC
When running a search like this: "eleições collection:BN" returns a list of results limited to the BN collection https://arquivo.pt/search.jsp?l=pt&query=elei%C3%A7%C3%B5es+collection%3ABN&btnSubmit=Pesquisar
Then, when I click on the "Images" button the parameter collection doesn't run, https://arquivo.pt/images.jsp?l=pt&query=elei%C3%A7%C3%B5es%20collection:BN&dateStart=01/01/1996&dateEnd=31/12/2018

**Comment by igobranco** [comment] 2019-11-05 09:56
Duplicate of #416

**Closed by igobranco** 2019-11-05 09:56 UTC
Labels: Component-Image Search
