### ISSUE TITLE
Click on Facebook thumbnail originates recursive replay

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#849] opened 2020-03-24 12:29 UTC
Consider this post:
https://www.facebook.com/Arquivo.pt/posts/3311940092169326

If we click on Facebook thumbnail originates a recursive replay:
![image](https://user-images.githubusercontent.com/13120352/77425465-a8bcfa80-6dca-11ea-800a-2075e3c4f01c.png)

However, if we click directly on the page wayback URL it looks OK:
https://arquivo.pt//wayback/19961013182714/http://www.publico.pt:80/publico/hoje/

**Comment by igobranco** [comment] 2020-03-25 11:57
Link with problem and isn't related with facebook: 
https://arquivo.pt/wayback/19961013182714/http://www.publico.pt:80/publico/hoje/Retomar

Other links, like the homepage of that page is ok:
https://arquivo.pt/wayback/19961013182714/http://www.publico.pt:80/

If you share other page everything seams ok, like:
https://arquivo.pt/wayback/19961013145650/http://www.fccn.pt/

Event when you click on both red dots on the post, view next image:
![image](https://user-images.githubusercontent.com/67018/77533066-19791b00-6e8e-11ea-9558-9f5aa49bc13e.png)

**Comment by igobranco** [comment] 2020-03-25 12:04
I think this is a pywb issue related with its rewrites.

**Comment by igobranco** [comment] 2020-03-25 12:05
@danielbicho please analyse it further.

**Comment by danielbicho** [comment] 2020-04-01 09:31
@igobranco I think this somehow stills an httpd problem, or part of it is our httpd, but I didn't find where.
I tested this bug with our framed pywb version without going through httpd and the problem doesn't show up.

I noticed that this weird redirecting just happen if an URL doesn't exist on the webarchive and if it has double // after the host on the URL.

So @dcgomes, you wanted to share https://arquivo.pt/wayback/19961013182714/http://www.publico.pt:80/publico/hoje/, but you ended sharing https://arquivo.pt//wayback/19961013182714/http://www.publico.pt:80/publico/hoje/Retomar. Don't know how that happen there, please try sharing the original resource again.

I also noticed that we are dealing with requests like https://arquivo.pt/////////////////////////////////////////////////// in a weid way, it should redirect or fix the URL to just https://arquivo.pt/, but it doesn't do that.

**Comment by igobranco** [comment] 2020-04-01 16:39
@danielbicho  You are right!

The problem is when we have many // and clicks from facebook that  include the fdclid attribute.

Like: 
https://arquivo.pt//wayback/19961013182714/http://www.publico.pt:80/publico/hoje/?fdclid=aaaa

Fix is a redirect like:
https://arquivo.pt//wayback....  ==> https://arquivo.pt/wayback...

**Comment by igobranco** [comment] 2020-04-06 10:45
I couldn't removed the double slash using apache rewrites. I've tried some examples on the web and can't put them to work.
Nevertheless is this issue relevant? Isn't this a race condition were the user constructs manually an URL?

**Comment by igobranco** [comment] 2020-04-21 14:21
I'm closing this issue. It seams not relevant.

**Closed by igobranco** 2020-04-21 14:21 UTC
Labels: Component-Replay-Wayback, Impact-Medium, Type-Bug
