### ISSUE TITLE
Result titles without bold

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#809] opened 2020-02-27 10:07 UTC
**What is the URL that originated the issue?**
https://m.preprod.arquivo.pt/search.jsp?query=leiria&l=pt&dateStart=01%2F01%2F1996&dateEnd=27%2F02%2F2020

**Screenshots**
1. In this case "leiria" sould be in bold. 

![2](https://user-images.githubusercontent.com/25795364/75433733-595ce900-5948-11ea-8fd2-be62c0da2e7b.JPG)

**Comment by igobranco** [comment] 2020-02-27 13:44
The problem is because the Text Search API isn't sending the title of the page with emphasized text like the snippet. 
View this response item:
![image](https://user-images.githubusercontent.com/67018/75450723-38f05700-5967-11ea-9286-7deaebbe58c5.png)

**Comment by igobranco** [comment] 2020-02-27 13:45
Changing the label of this issue to be related with the API backend.

**Comment by igobranco** [comment] 2020-02-28 10:29
After a talk with @danielbicho we decided that changing the result "title" field of the Page Search API (text search) could have other side effects like other applications that use ours API could be broken. 
Because this issue is related to the presentation, is could be resolved on client side using Javascript.

**Comment by igobranco** [comment] 2020-02-28 10:30
@dcgomes is this relevant? Or we could close this issue has "won't do".

**Comment by igobranco** [comment] 2020-03-12 12:03
yes we need bold.

**Closed** 2020-03-13 09:58 UTC
Labels: Component-SearchPages-SearchPageAPI, Impact-Low, Type-Bug
