### ISSUE TITLE
css not loaded for page "Festival da Canção"

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#11] opened 2015-06-26 16:05 UTC
Originally reported on Google Code with ID 12
```
What steps will reproduce the problem?
1. http://p15.arquivo.pt/wayback/wayback/id906088index4
2. when clicked on 'inicio/home' the exact same page is showed with the css

What is the expected output? What do you see instead?

The first links should also load the css.

Please use labels and text to provide additional information.


```

Reported by `migcosta` on 2012-01-31 18:55:45

**Comment by Fernando-Melo** [comment] 2015-11-30 12:15
arquivo.pt//wayback/wayback/id906088index4 gives Resource Index Not Available Exception .
Was the page lost? Can't reproduce the error. Maybe close this issue?

**Comment by Fernando-Melo** [comment] 2015-11-30 12:23
New url of the page: http://arquivo.pt//wayback/wayback/id906088index17

**Comment by Fernando-Melo** [comment] 2015-11-30 12:34
Css is loaded tested on windows with chrome

**Closed by Fernando-Melo** 2015-11-30 12:34 UTC
Labels: Impact-Low
