### ISSUE TITLE
Wrong link in the user interface "technical details"

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#1047] opened 2020-11-16 11:50 UTC
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20181019010245/http://a-praia.blogspot.com/#  (technical details (field description)

**What happened?**
The link opens a form to create a new page: https://github.com/arquivo/pwa-technologies/wiki/Arquivo.pt-API-v.0.2#response-fields

**What should have happened?**
Should open the field description

**Screenshots**
<img width="958" alt="2020_11_16_11_38_33_" src="https://user-images.githubusercontent.com/44206545/99249003-4acd9f00-2801-11eb-80e3-13d990c34e8e.png">

**Comment by amourao** [comment] 2021-01-14 17:11
Duplicate of https://github.com/arquivo/pwa-technologies/issues/1022

**Closed by amourao** 2021-01-14 17:11 UTC
Labels: Component-Replay-Wayback, Impact-Low, Type-Enhancement
