### ISSUE TITLE
Add spam filter for imagesearch

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#546] opened 2019-07-02 09:39 UTC
Add a spam field to all solr documents.
For now the field will have a value of 0 or 1 if the domain is in our spam list. 
Change ranking of images so it gives negative boost to documents with spam=1

**Comment by Fernando-Melo** [comment] 2019-07-02 10:47
Add field equals to 1 if the image document timestamp is within the period that was considered spam.
Use timestamps provided by Ricardo Basílio and add 1month before and 1 month after.

**Comment by amourao** [comment] 2020-02-07 16:23
This step will be performed as the NSFW classifier is done currently:

- After extracting image information from WARCS, run a classifier that looks into the page/image url information and updates the information in the _spam_ field on JSONL
- This way, (and after implementing unique doc key on Solr), when new domains are added to the spam list, you only need to run this classifier again and send to Solr only the JSON lines whose status changed.
- Consider finding a way of doing this reclassification procedure on Solr to avoid resending documents again.

**Comment by amourao** [comment] 2020-02-07 16:23
Duplicate of #771.

**Closed by amourao** 2020-02-07 16:23 UTC
Labels: Component-SearchImages-ImageSearchAPI, Type-Enhancement
