### ISSUE TITLE
Some URLs not recognized as valid URL on SavePageNow

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#1209] opened 2021-12-07 10:57 UTC
**What is the URL that originated the issue?**
https://www.portugal.gov.pt/pt/gc21/comunicacao/noticia?i=ministro-da-defesa-nacional-reuniu-se-na-nato-para-discutir-desafios-de-seguranca

**What happened?**
When put on SavePageNow says the URL is not correct

**What should have happened?**
This URL is correct on the live Web, so should be recorded as a normal link.

**Screenshots**
<img width="958" alt="2021_12_06_17_00_47_Fotografias" src="https://user-images.githubusercontent.com/44206545/145015766-1ec43bd6-09a7-4a27-a4bd-b512dc6eed1c.png">

**Comment by VascoRatoFCCN** [comment] 2022-08-03 14:36
Closing this issue because the cause is the same as https://github.com/arquivo/pwa-technologies/issues/1284

**Closed by VascoRatoFCCN** 2022-08-03 14:36 UTC
Labels: Impact-Medium, Impact-High, Type-Bug, Component-DataAcquisition-SavePageNow
