### ISSUE TITLE
CSS from Wordpress.com sites are not being crawled/rendered?

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#133] opened 2015-06-26 17:06 UTC
Originally reported on Google Code with ID 134
```
I identified that the archived versions of several sites hosted under Wordpress.com
are being correctly rendered:
- http://arquivo.pt/wayback/wayback/20131105154232/http://tararecuperavel.org/
- http://arquivo.pt/wayback/wayback/20131105154229/http://ajologoexisto.wordpress.com/
- http://arquivo.pt/wayback/wayback/20131105154240/http://antinatoportugal.wordpress.com/

It seems that the CSS are missing.

On the other hand, I identified that other Wordpress.com work OK:

- http://arquivo.pt/wayback/wayback/20080317192343/http://mocambique.wordpress.com/
- http://arquivo.pt/wayback/wayback/id83149index9?pos=49&l=pt&sid=53BA08004372510D55698F3F66469D0D
(http://filosofiacritica.wordpress.com/)
- http://arquivo.pt/wayback/wayback/id24732987index16?year=2008&r_pos=1&r_t=1&col_pos=1&col_tot=1&l=pt&sid=53BA08004372510D55698F3F66469D0D
(http://vnet.wordpress.com/)

And noticed that the problem occurs only on some versions of the same site (http://maquinazero.wordpress.com/):

http://arquivo.pt/search.jsp?l=pt&query=http%3A%2F%2Fmaquinazero.wordpress.com&btnSubmit=Pesquisar+no+Arquivo&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2014

OK (2008):
http://arquivo.pt/wayback/wayback/id4776index15?year=2008&r_pos=1&r_t=2&col_pos=1&col_tot=6&l=pt&sid=53BA08004372510D55698F3F66469D0D
OK (2011):
http://arquivo.pt/wayback/wayback/id4014index30?year=2011&r_pos=1&r_t=3&col_pos=4&col_tot=6&l=pt&sid=53BA08004372510D55698F3F66469D0D
Not OK (2013):
http://arquivo.pt/wayback/wayback/id19802index14?year=2013&r_pos=1&r_t=1&col_pos=6&col_tot=6&l=pt&sid=53BA08004372510D55698F3F66469D0D

The robots.txt seems to allow the crawl of the CSS. May it be some problem with the
deduplication?

Verify that we are crawling all the required CSS on the next crawl and check if they
are rendered. 

Check for instance the suggested site: https://arquivosap.wordpress.com/

We must verify if we have any problem with Wordpress.com hosted sites because this
platform currently hosts many sites. 
```

Reported by `danielcoelhogomes` on 2015-06-11 18:20:39

**Comment by Eversong** [comment] 2015-07-09 10:57
In this example:
http://arquivo.pt/wayback/wayback/id19802index14?year=2013&r_pos=1&r_t=1&col_pos=6&col_tot=6&l=pt&sid=53BA08004372510D55698F3F66469D0D

There is nothing in site poiting to the style.css, that is used in  older versions of the site. This is a problem in the construction of the site when the it was crawled. You can check that this link that still available in live web is pointing for a blank document:

 http://arquivo.pt/wayback/wayback/20131107213156/http://s2.wp.com/_static/??-eJyNkeFuwjAMhF+I4DHGuj9oz5I2ITE4cVS7qnh7olZilUDR/l2U73RnG+ZiBs7qs0KaTKEpYBZI5dtEO9w2aj+I7OA9TnjzAlevpZJmeb3gPXH4M3AI3vGk5sJEPMOMLnhtZWC+YEa9P8W/YI0+1Wpl6mHBUmmGSORRB3bVUikQwiojz+b50XIXljoQWRxB9E6v7Js2bTJ+QSDuLbVi192tjVdtwojO2OzqLaQ58NYbmN3orVtu95vOh+PPsTt9dJ+n6wP1v88M

In olders versions of the site this should be the style.css.
Other usually crawled stylesheets were crawled correctly (global-print.css)

**Comment by dcgomes** [comment] 2015-11-27 16:06
Check if problem persists with PyWB.

**Comment by Fernando-Melo** [comment] 2016-03-04 18:03
Yes problem persists with PyWb.
From what I've read it has nothing to do with the Wayback.
There are 2 options:
1) The css files were not extracted during the crawling process (there is nothing we can do so we should close this issue)
2) The css files were extracted during the crawling process (i.e. they exist in the arc files) but opensearch is not returning the css files #164 (problems indexing)

**Comment by FCCNhviana** [comment] 2016-04-22 10:59
The robots.txt of the site http://maquinazero.wordpress.com/ has been changed over the years, and now it disallows the harvest of /wp-includes/. wp-includes contains everything needed to run WordPress via the frontend ( and then some ). It is the territory of WordPress Core. (http://wordpress.stackexchange.com/questions/74940/what-is-the-wordpress-wp-includes-folder-for).
The following URLs screens the robots.txt evolution through the years:

http://arquivo.pt/wayback/20140907064202/http://maquinazero.wordpress.com/robots.txt
http://arquivo.pt/wayback/20080223094042/http://maquinazero.wordpress.com/robots.txt
http://arquivo.pt/wayback/20110126063243/http://maquinazero.wordpress.com/robots.txt
http://arquivo.pt/wayback/20131107212721/http://maquinazero.wordpress.com/robots.txt

Therefore, we can not reproduce properly this archived web content.

It was suggested to crawl https://arquivosap.wordpress.com/ because Arquivo.pt does not contains this URL's on the seeds.

**Comment by FCCNhviana** [comment] 2016-04-26 12:00
I recommend to remove this issue from the Janus milestone.

**Comment by FCCNhviana** [comment] 2016-04-27 09:07
This is a Robots.txt issue, for solving it we have to contact the owners to change the Robots.txt in order to crawl better.

**Closed by FCCNhviana** 2016-04-27 09:07 UTC
Labels: Component-Heritrix, Component-Nutchwax, Impact-Medium, Type-Bug
